#!/bin/bash
set -eux

ROOT="$(dirname "$(readlink -f "$0")")"
MODULES_DIR="${ROOT}"/deployment_scripts/puppet/modules
RPM_REPO="${ROOT}"/repositories/centos/
DEB_REPO="${ROOT}"/repositories/ubuntu/
HEKA_VERSION="0.9.2"
FUEL_LIB_VERSION="6.0"
FUEL_LIB_TARBALL_URL="http://192.168.5.19/fuel-library/${FUEL_LIB_VERSION}.tar.gz"
COLLECTD_TARBALL_URL="http://192.168.5.19/fuel-plugins-tarball/pdxcat-collectd-3.2.0.tar.gz"
APACHE_TARBALL_URL="http://192.168.5.19/fuel-plugins-tarball/puppetlabs-apache-1.4.0.tar.gz"

function download_packages {
    while [ $# -gt 0 ]; do
        FILENAME=$(basename "$1")
        EXT=${FILENAME##*.}
        case ${EXT} in
            rpm) REPO=$RPM_REPO;;
        esac

        rm -f "$REPO"/"$FILENAME"
        wget -qO - "$1" > "$REPO"/"$FILENAME"
        shift
    done
}

download_packages \
    http://192.168.5.19/fuel-plugins/centos/Packages/heka-${HEKA_VERSION//./_}-linux-amd64.rpm > "${RPM_REPO}"/heka-${HEKA_VERSION//./_}-linux-amd64.rpm \
    http://192.168.5.19/fuel-plugins/centos/Packages/libdbi-0.8.4-6.el7.x86_64.rpm \
    http://192.168.5.19/fuel-plugins/centos/Packages/libdbi-drivers-0.8.3-16.el7.x86_64.rpm \
    http://192.168.5.19/fuel-plugins/centos/Packages/libdbi-dbd-mysql-0.8.3-16.el7.x86_64.rpm \
    http://192.168.5.19/fuel-plugins/centos/Packages/collectd-5.4.1-5.eayunstack.1.0.x86_64.rpm \
    http://192.168.5.19/fuel-plugins/centos/Packages/collectd-apache-5.4.1-5.eayunstack.1.0.x86_64.rpm \
    http://192.168.5.19/fuel-plugins/centos/Packages/collectd-dbi-5.4.1-5.eayunstack.1.0.x86_64.rpm \
    http://192.168.5.19/fuel-plugins/centos/Packages/collectd-mysql-5.4.1-5.eayunstack.1.0.x86_64.rpm


# Extract dependent manifests from fuel-library
rm -rf "${MODULES_DIR:?}"/{cinder,glance,heat,inifile,keystone,neutron,nova,openstack,stdlib,concat}
wget -qO- "${FUEL_LIB_TARBALL_URL}" | \
    tar -C "${MODULES_DIR}" --strip-components=3 -zxvf - \
    fuel-library-${FUEL_LIB_VERSION}/deployment/puppet/{cinder,glance,heat,inifile,keystone,neutron,nova,openstack,stdlib,concat}

rm -rf "${MODULES_DIR:?}"/collectd
mkdir -p "${MODULES_DIR}"/collectd
wget -qO- "${COLLECTD_TARBALL_URL}" | tar -C "${MODULES_DIR}/collectd" --strip-components=1 -xz

# Apache is not available in Fuel 6.0. It will be available in 6.1. So until the switch to 6.1
# we download it from puppetlabs.
rm -rf "${MODULES_DIR:?}"/apache
mkdir -p "${MODULES_DIR}"/apache
wget -qO- "${APACHE_TARBALL_URL}" | tar -C "${MODULES_DIR}/apache" --strip-components=1 -xz
